import monstera from '../assets/monstera.jfif'

export const plants = [
	{
		name: 'Rose',
		category: 'Fleurs',
		id: '1ed',
		isPremium: false,
		isSpecialOffer : false,
		water:2,
		light:2,
		cover:monstera,
		price:6,
	},
	{
		name: 'Tulipe',
		category: 'Fleurs',
		id: '2ab',
		isPremium: false,
		isSpecialOffer : false,
		water:2,
		light:2,
		cover:monstera,
		price:6,
	},
	{
		name: 'Orchidée',
		category: 'Fleurs',
		id: '3sd',
		isPremium: true,
		isSpecialOffer : false,
		water:1,
		light:1,
		cover:monstera,
		price:9,
	},
	{
		name: 'Lys',
		category: 'Fleurs',
		id: '4kk',
		isPremium: true,
		isSpecialOffer : false,
		water:1,
		light:1,
		cover:monstera,
		price:8,
	},
	{
		name: 'Petit Bouquet',
		category: 'Compositions',
		id: '5pl',
		isPremium: false,
		isSpecialOffer : false,
		water:3,
		light:3,
		cover:monstera,
		price:20,
	},
	{
		name: 'Grand Bouquet',
		category: 'Compositions',
		id: '6uo',
		isPremium: false,
		isSpecialOffer : true,
		water:3,
		light:3,
		cover:monstera,
		price:35,
	},
	{
		name: 'Cactus',
		category: 'Plantes Grasses',
		id: '7ie',
		isPremium: false,
		isSpecialOffer : false,
		water:1,
		light:3,
		cover:monstera,
		price:12,
	},
	{
		name: 'Aloe',
		category: 'Plantes Grasses',
		id: '8fp',
		isPremium: false,
		isSpecialOffer : false,
		water:2,
		light:3,
		cover:monstera,
		price:12,
	},
	{
		name: 'Succulente',
		category: 'Plantes Grasses',
		id: '9vn',
		isPremium: false,
		isSpecialOffer : true,
		water:1,
		light:3,
		cover:monstera,
		price:12,
	}
]